using System.Data.Common;
using System.Text.RegularExpressions;
using Microsoft.Data.Sqlite;
using Npgsql;

namespace CrcInventory.Server;

/// <summary>
/// SQLite files by default. Postgres (Digital Ocean) when a connection string is set.
/// Live and archive map to crc_inventory.db / old_inventory.db, or schemas live / archive.
/// </summary>
internal abstract class StoreEngine
{
    public abstract string Name { get; }
    public abstract bool IsPostgres { get; }
    public abstract string IdColumn { get; }
    public abstract string BlobType { get; }
    public abstract string NoCaseText { get; }

    public abstract DbConnection Open(bool archive);
    public abstract IReadOnlyList<string> ListColumns(DbConnection db, string table);
    public abstract void Prepare(DbCommand cmd);

    public static string Quote(string name) => "\"" + name.Replace("\"", "\"\"") + "\"";

    public static StoreEngine Sqlite(string folder) => new SqliteStoreEngine(folder);

    public static StoreEngine Postgres(string connectionString) =>
        new PostgresStoreEngine(connectionString);
}

internal static class DbCmd
{
    public static void AddParam(this DbCommand cmd, string name, object? value)
    {
        var parameter = cmd.CreateParameter();
        parameter.ParameterName = name;
        parameter.Value = value ?? DBNull.Value;
        if (value is byte[])
            parameter.DbType = System.Data.DbType.Binary;
        cmd.Parameters.Add(parameter);
    }

    public static int Exec(this DbCommand cmd, StoreEngine engine)
    {
        engine.Prepare(cmd);
        return cmd.ExecuteNonQuery();
    }

    public static DbDataReader Query(this DbCommand cmd, StoreEngine engine)
    {
        engine.Prepare(cmd);
        return cmd.ExecuteReader();
    }

    public static object? Scalar(this DbCommand cmd, StoreEngine engine)
    {
        engine.Prepare(cmd);
        return cmd.ExecuteScalar();
    }
}

internal sealed class SqliteStoreEngine : StoreEngine
{
    private readonly string _folder;

    public SqliteStoreEngine(string folder) => _folder = folder;

    public override string Name => "sqlite (local files)";
    public override bool IsPostgres => false;
    public override string IdColumn => "id INTEGER PRIMARY KEY AUTOINCREMENT";
    public override string BlobType => "BLOB";
    public override string NoCaseText => "TEXT NOT NULL COLLATE NOCASE";

    public override DbConnection Open(bool archive)
    {
        string path = Path.Combine(
            _folder,
            archive ? Schema.ArchiveFileName : Schema.LiveFileName);
        var db = new SqliteConnection(new SqliteConnectionStringBuilder
        {
            DataSource = path,
            Mode = SqliteOpenMode.ReadWriteCreate,
            DefaultTimeout = 8
        }.ToString());
        db.Open();
        using var pragma = db.CreateCommand();
        pragma.CommandText = "PRAGMA busy_timeout=8000;";
        pragma.ExecuteNonQuery();
        return db;
    }

    public override IReadOnlyList<string> ListColumns(DbConnection db, string table)
    {
        var list = new List<string>();
        using var cmd = db.CreateCommand();
        cmd.CommandText = $"PRAGMA table_info({Quote(table)});";
        using var reader = cmd.ExecuteReader();
        while (reader.Read())
            list.Add(reader.GetString(1));
        return list;
    }

    public override void Prepare(DbCommand cmd)
    {
    }
}

internal sealed class PostgresStoreEngine : StoreEngine
{
    private static readonly Regex DollarParams = new(@"\$([A-Za-z_][A-Za-z0-9_]*)", RegexOptions.Compiled);
    private readonly string _connectionString;
    private readonly object _bootLock = new();
    private bool _bootstrapped;

    public PostgresStoreEngine(string connectionString)
    {
        _connectionString = Normalize(connectionString);
    }

    public override string Name => "postgres (Digital Ocean)";
    public override bool IsPostgres => true;
    public override string IdColumn => "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
    public override string BlobType => "BYTEA";
    public override string NoCaseText => "CITEXT NOT NULL";

    public override DbConnection Open(bool archive)
    {
        var db = new NpgsqlConnection(_connectionString);
        db.Open();
        Bootstrap(db);
        using var path = db.CreateCommand();
        path.CommandText = archive
            ? "SET search_path TO archive, public"
            : "SET search_path TO live, public";
        path.ExecuteNonQuery();
        return db;
    }

    public override IReadOnlyList<string> ListColumns(DbConnection db, string table)
    {
        var list = new List<string>();
        using var cmd = db.CreateCommand();
        cmd.CommandText =
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = @table
            ORDER BY ordinal_position;
            """;
        var parameter = cmd.CreateParameter();
        parameter.ParameterName = "@table";
        parameter.Value = table;
        cmd.Parameters.Add(parameter);
        using var reader = cmd.ExecuteReader();
        while (reader.Read())
            list.Add(reader.GetString(0));
        return list;
    }

    public override void Prepare(DbCommand cmd)
    {
        string sql = cmd.CommandText ?? "";
        sql = DollarParams.Replace(sql, "@$1");
        sql = sql.Replace("COLLATE NOCASE", "", StringComparison.OrdinalIgnoreCase);
        sql = sql.Replace("last_insert_rowid()", "lastval()", StringComparison.OrdinalIgnoreCase);
        cmd.CommandText = sql;
        foreach (DbParameter parameter in cmd.Parameters)
        {
            string name = parameter.ParameterName ?? "";
            if (name.StartsWith('$'))
                parameter.ParameterName = "@" + name[1..];
        }
    }

    private void Bootstrap(NpgsqlConnection db)
    {
        if (_bootstrapped)
            return;
        lock (_bootLock)
        {
            if (_bootstrapped)
                return;
            using var cmd = db.CreateCommand();
            cmd.CommandText =
                """
                CREATE EXTENSION IF NOT EXISTS citext;
                CREATE SCHEMA IF NOT EXISTS live;
                CREATE SCHEMA IF NOT EXISTS archive;
                """;
            cmd.ExecuteNonQuery();
            _bootstrapped = true;
        }
    }

    internal static string Normalize(string raw)
    {
        raw = (raw ?? "").Trim();
        if (raw.Length == 0)
            throw new InvalidOperationException("Postgres connection string is empty.");

        if (raw.StartsWith("postgres://", StringComparison.OrdinalIgnoreCase) ||
            raw.StartsWith("postgresql://", StringComparison.OrdinalIgnoreCase))
        {
            var uri = new Uri(raw);
            string userInfo = uri.UserInfo ?? "";
            int colon = userInfo.IndexOf(':');
            string user = Uri.UnescapeDataString(colon < 0 ? userInfo : userInfo[..colon]);
            string password = colon < 0 ? "" : Uri.UnescapeDataString(userInfo[(colon + 1)..]);
            string database = uri.AbsolutePath.Trim('/');
            var fromUri = new NpgsqlConnectionStringBuilder
            {
                Host = uri.Host,
                Port = uri.IsDefaultPort
                    ? (uri.Host.Contains("ondigitalocean.com", StringComparison.OrdinalIgnoreCase) ? 25060 : 5432)
                    : uri.Port,
                Database = database.Length > 0 ? database : "defaultdb",
                Username = user,
                Password = password,
                SslMode = SslMode.Require
            };
            return fromUri.ToString();
        }

        var builder = new NpgsqlConnectionStringBuilder(raw);
        if (builder.SslMode is SslMode.Disable or SslMode.Allow or SslMode.Prefer)
            builder.SslMode = SslMode.Require;
        if (builder.Port == 5432 &&
            (builder.Host ?? "").Contains("ondigitalocean.com", StringComparison.OrdinalIgnoreCase))
            builder.Port = 25060;
        return builder.ToString();
    }
}
